name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Cache Coursier
        uses: actions/cache@v3
        with:
          path: ~/.coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Check Scala format
        run: sbt scalafmtCheckAll

      - name: Build project
        run: sbt compile

      - name: Test
        run: sbt test
